export type GuideBlock = {
  heading: string;
  items: string[];
  ordered?: boolean;
  tone?: "default" | "warning" | "success";
};

export type GuideEntry = {
  id: string;
  title: string;
  summary: string;
  aliases: string[];
  href?: string;
  blocks: GuideBlock[];
};

export type GuideSection = {
  id: string;
  title: string;
  description: string;
  entries: GuideEntry[];
};

type PlaybookInput = Omit<GuideEntry, "blocks"> & {
  when: string[];
  before: string[];
  steps: string[];
  impact: string[];
  mistakes: string[];
  rollback: string[];
};

const playbook = ({ when, before, steps, impact, mistakes, rollback, ...entry }: PlaybookInput): GuideEntry => ({
  ...entry,
  blocks: [
    { heading: "متى تستخدمه؟", items: when },
    { heading: "قبل أن تبدأ", items: before },
    { heading: "الخطوات", items: steps, ordered: true },
    { heading: "ما الذي يتأثر؟", items: impact, tone: "success" },
    { heading: "أخطاء شائعة", items: mistakes, tone: "warning" },
    { heading: "التعديل أو التراجع", items: rollback },
  ],
});

const reference = (
  id: string,
  title: string,
  summary: string,
  aliases: string[],
  href: string,
  owns: string[],
  fields: string[],
  warnings: string[],
): GuideEntry => ({
  id,
  title,
  summary,
  aliases,
  href,
  blocks: [
    { heading: "مسؤولية الصفحة", items: owns },
    { heading: "الحقول والأوامر المهمة", items: fields },
    { heading: "انتبه", items: warnings, tone: "warning" },
  ],
});

const troubleshooting = (
  id: string,
  title: string,
  aliases: string[],
  href: string,
  checks: string[],
): GuideEntry => ({
  id,
  title,
  summary: "راجع النقاط التالية بالترتيب؛ توقف عند أول سبب غير صحيح وصححه ثم اختبر مرة أخرى.",
  aliases,
  href,
  blocks: [{ heading: "خطوات التشخيص", items: checks, ordered: true }],
});

const understandSystem: GuideEntry[] = [
  {
    id: "core-records",
    title: "الفرق بين Offering وAvailability وSession وProgram وBooking",
    summary: "هذه السجلات مرتبطة ببعضها، لكن كل واحد منها يملك جزءًا مختلفًا من رحلة الحجز.",
    aliases: ["offering", "availability", "session", "program", "booking", "خدمة", "إتاحة", "سيشن", "برنامج", "حجز"],
    blocks: [
      {
        heading: "المعاني",
        items: [
          "Offering هو تعريف الخدمة: الاسم والوصف والنوع وطريقة الحضور والحجز والمدة والسعة الافتراضية وحالة النشر.",
          "Availability هي نوافذ أسبوعية متكررة لخدمات Appointment slots؛ مثل الثلاثاء من 09:00 إلى 13:00.",
          "Session هي موعد ثابت له Starts وEnds ويخص Offering محدد؛ تستخدم لموعد بتاريخ معلوم بدل جدول أسبوعي متكرر.",
          "Program هو تسجيل واحد في Event أو Workshop أو Course كامل، ويمكن أن يحتوي Occurrence واحدة أو عدة Occurrences.",
          "Booking هو الحجز الذي أنشأه العميل فعلًا؛ لا تنشئ Offering أو Availability بدلًا منه.",
          "Location هو المكان القابل لإعادة الاستخدام في الحضور Offline أو Hybrid.",
        ],
      },
      {
        heading: "ترتيب الاعتماد",
        items: [
          "ابدأ دائمًا بإنشاء Offering وحفظها؛ بعدها أضف السعر والإتاحة أو Session أو Program حسب نوع الجدولة.",
          "أنشئ Location قبل Session أو Program إذا كان الحضور Offline أو Hybrid.",
          "اختبر ما يراه العميل قبل نشر الرابط أو بدء حملة تسويق.",
        ],
        ordered: true,
      },
    ],
  },
  {
    id: "scheduling-decision",
    title: "أختار Appointment slots ولا Session ولا Program؟",
    summary: "اختيار Scheduling type الصحيح يمنع تكرار المواعيد أو ظهور تجربة حجز غير مناسبة.",
    aliases: ["scheduling type", "appointment slots", "scheduled program", "قرار", "ميعاد ثابت", "كورس"],
    blocks: [
      {
        heading: "شجرة القرار",
        items: [
          "اختر Appointment slots عندما يختار العميل موعدًا من ساعات متكررة كل أسبوع، مثل 1:1 Coaching.",
          "استخدم Sessions عندما تريد موعدًا ثابتًا مستقلًا بتاريخ ووقت وسعة محددين.",
          "اختر Scheduled program ثم Events & Programs عندما يسجل العميل مرة واحدة في ورشة أو Event أو كورس له موعد أو عدة مواعيد.",
          "لا تضف Availability لخدمة Scheduled program؛ مواعيدها تأتي من Occurrences داخل Program.",
        ],
      },
    ],
  },
  {
    id: "statuses",
    title: "معاني Draft وPublished وScheduled وArchived",
    summary: "حالة السجل تحدد هل ما زال تحت التجهيز، ظاهرًا، مؤجل النشر، أو خارج الاستخدام.",
    aliases: ["draft", "published", "scheduled", "archived", "status", "حالة", "نشر", "أرشفة"],
    blocks: [
      {
        heading: "الحالات",
        items: [
          "Draft: نسخة عمل غير جاهزة للاعتماد العام. استخدمها أثناء إدخال البيانات والمراجعة.",
          "Published: السجل معتمد للاستخدام العام، بشرط اكتمال بقية الاعتمادات مثل السعر والإتاحة.",
          "Scheduled: النشر أو الموعد مرتبط بوقت محدد حسب الصفحة التي تستخدم الحالة.",
          "Archived: السجل محفوظ للتاريخ لكنه خارج التشغيل العادي. الأرشفة هي الخيار الآمن عندما توجد سجلات مرتبطة.",
        ],
      },
    ],
  },
  {
    id: "capacity-states",
    title: "الفرق بين Booked وHeld وRemaining",
    summary: "السعة المتاحة ليست دائمًا Capacity ناقص الحجوزات المؤكدة فقط.",
    aliases: ["booked", "held", "remaining", "capacity", "محجوز", "معلق", "متبقي", "سعة"],
    blocks: [
      {
        heading: "الحساب",
        items: [
          "Booked هي المقاعد المرتبطة بحجوزات مؤكدة أو محسوبة ضمن الإشغال.",
          "Held هي مقاعد محجوزة مؤقتًا أثناء إكمال العميل للحجز أو الدفع، وقد تعود تلقائيًا بعد انتهاء المهلة.",
          "Remaining هو المتبقي بعد خصم Booked وHeld من السعة الكلية وفق قواعد النظام.",
          "إذا ظهر المكان ممتلئًا مؤقتًا، راجع Held قبل رفع Capacity بلا داعٍ.",
        ],
      },
    ],
  },
];

const playbooks: GuideEntry[] = [
  playbook({
    id: "create-appointment-offering",
    title: "إنشاء خدمة 1:1 قابلة للحجز من الصفر",
    summary: "إنشاء Offering بنظام Appointment slots ثم ضبط السعر والإتاحة ونشرها للعميل.",
    aliases: ["offerings", "availability", "1:1", "appointment slots", "coaching", "خدمة", "جلسة فردية"],
    href: "/admin/offerings/new",
    when: ["عندما تريد أن يختار العميل موعدًا من جدول أسبوعي متكرر، مثل 1:1 Coaching أو Therapy session."],
    before: ["حدد اسم الخدمة ومدتها وطريقة الحضور والحجز والسعر والسعة.", "أنشئ Location أولًا إذا كانت الخدمة Offline أو Hybrid."],
    steps: [
      "افتح Offerings واضغط New offering.",
      "أدخل Title وSlug وShort description، واختر Offering type المناسب.",
      "اختر Scheduling type = Appointment slots، ثم Attendance وBooking mode.",
      "اضبط Duration وBuffer before وBuffer after وCapacity. في خدمة فردية تكون Capacity عادة 1.",
      "احفظ Offering أولًا، ثم أضف Base amount أو Price groups من جزء التسعير.",
      "افتح Availability وأضف نوافذ الأيام والساعات الخاصة بهذه Offering بحالة Published.",
      "راجع Booking policy للتأكد من الحد الأدنى للحجز المسبق، ثم اختبر صفحة الحجز كعميل.",
      "غيّر Status إلى Published فقط بعد اكتمال السعر والإتاحة والتجربة.",
    ],
    impact: ["عنوان ووصف الخدمة يظهران في رحلة العميل.", "Duration وBuffers يحددان توزيع Slots داخل نافذة الإتاحة.", "Capacity تحدد عدد العملاء المقبولين في الموعد نفسه."],
    mistakes: ["نشر Offering بدون Availability يؤدي إلى خدمة بلا مواعيد.", "استخدام Scheduled program بدل Appointment slots يلغي منطق المواعيد الأسبوعية.", "تغيير Slug بعد مشاركة الرابط قد يكسر الروابط القديمة."],
    rollback: ["ارجع Status إلى Draft أثناء التصحيح إذا لم تبدأ حجوزات فعلية.", "استخدم Archive بدل الحذف عندما أصبحت الخدمة مستخدمة.", "عدّل نافذة الإتاحة بدل إنشاء نافذة متداخلة معها."],
  }),
  playbook({
    id: "add-fixed-session",
    title: "إضافة Session ثابتة",
    summary: "إضافة موعد محدد له تاريخ ووقت وسعة وربطه بخدمة موجودة.",
    aliases: ["sessions", "session", "add", "fixed date", "سيشن", "موعد ثابت"],
    href: "/admin/sessions",
    when: ["عندما يكون لديك موعد واحد بتاريخ معلوم ولا تريد أن يختاره العميل من Availability أسبوعية."],
    before: ["أنشئ Offering المناسبة أولًا وتأكد أنها غير Archived.", "أنشئ Location إذا كان الموعد Offline أو Hybrid."],
    steps: [
      "افتح Sessions واختر Offering من النموذج.",
      "حدد Starts وEnds بدقة وتأكد أن Ends بعد Starts.",
      "راجع Mode؛ إذا كانت Offering ليست Hybrid فسيفرض النظام طريقة الحضور المتوافقة.",
      "أدخل Capacity الخاصة بهذه Session، فهي سعة الموعد نفسه.",
      "اختر Location للحضور Offline أو Hybrid، واتركها فارغة للموعد Online.",
      "اكتب Timezone بصيغة IANA مثل Africa/Cairo.",
      "اترك Calendar event id فارغًا إلا إذا كنت تربط حدثًا معروفًا يدويًا.",
      "اختر Status المناسب واضغط Add، ثم راجع الصف الجديد في الجدول.",
    ],
    impact: ["العميل يحجز الموعد المحدد المرتبط بالـOffering.", "Capacity هنا تخص هذه Session ولا تعني تعديل كل Sessions الأخرى.", "Location وTimezone يؤثران في عرض مكان ووقت الموعد."],
    mistakes: ["اختيار Offering خاطئة يجعل الحجز يظهر تحت خدمة غير مقصودة.", "إدخال توقيت محلي مع Timezone خاطئة يغيّر الساعة المعروضة.", "الحضور Offline أو Hybrid لن يُحفظ بلا Location."],
    rollback: ["استخدم Edit لتعديل الموعد إذا كانت سياسة التشغيل تسمح بذلك.", "تحقق من الحجوزات قبل تغيير الوقت أو السعة.", "استخدم Archive لإخراج Session من التشغيل مع الاحتفاظ بتاريخها."],
  }),
  playbook({
    id: "create-one-off-program",
    title: "إنشاء Event أو Workshop بموعد واحد",
    summary: "إنشاء Program له Occurrence واحدة ويقوم العميل بالتسجيل فيه مرة واحدة.",
    aliases: ["programs", "events", "workshop", "webinar", "occurrence", "ورشة", "حدث"],
    href: "/admin/programs",
    when: ["عندما يكون المنتج Event أو Workshop أو Webinar بتاريخ ثابت وتريد Enrollment كاملًا بدل Slot فردية."],
    before: ["أنشئ Offering واجعل Scheduling type = Scheduled program.", "اضبط السعر وLocation إن لزم قبل نشر البرنامج."],
    steps: [
      "افتح Events & Programs واضغط New Program.",
      "اختر Offering التي تعمل بنظام Scheduled program.",
      "أدخل Program title وTimezone وAttendance وEnrollment capacity.",
      "حدد Registration opens وRegistration closes؛ يجب أن يكون الإغلاق قبل أول Occurrence.",
      "احتفظ بـOccurrence واحدة وحدد Starts وEnds وTimezone وLocation وStatus = Scheduled.",
      "اضغط Create draft وراجع كل البيانات في Enrollment inventory.",
      "اضغط Publish عندما تصبح البيانات جاهزة، ثم راقب Calendar sync وMeet link إن كان Online.",
    ],
    impact: ["العميل يسجل مرة واحدة في البرنامج كله.", "Enrollment capacity هي العدد الأقصى للبرنامج وليست لكل جزء مستقل.", "النشر قد ينشئ أو يزامن أحداث التقويم حسب إعداد التكامل."],
    mistakes: ["إنشاء Program قبل Offering بنظام Scheduled program يجعل قائمة Offering خالية.", "Registration closes بعد بداية الحدث غير صالح.", "نشر البرنامج قبل مراجعة Timezone قد يرسل مواعيد خاطئة للعملاء."],
    rollback: ["عدّل الـDraft قبل النشر بحرية.", "بعد وجود تسجيلات، راجع تأثير تغيير الوقت أو المكان على العملاء والتقويم.", "استخدم Archive عندما لا يكون الحذف متاحًا بسبب الاستخدام."],
  }),
  playbook({
    id: "create-course-program",
    title: "إنشاء كورس له عدة مواعيد",
    summary: "Program واحدة تحتوي عدة Occurrences؛ العميل يسجل مرة واحدة في الكورس كاملًا.",
    aliases: ["programs", "course", "occurrences", "cohort", "كورس", "دفعة", "مواعيد متعددة"],
    href: "/admin/programs",
    when: ["عندما يتكون الكورس أو الدفعة من أكثر من لقاء وكل المشتركين يحضرون السلسلة كاملة."],
    before: ["أنشئ Course Offering بنظام Scheduled program.", "جهز جدول كل اللقاءات وTimezone وLocation قبل الإدخال."],
    steps: [
      "أنشئ Program وحدد Offering وProgram title والسعة وفترة التسجيل.",
      "اضبط أول Occurrence بتاريخ البداية والنهاية الصحيحين.",
      "اضغط Add occurrence لكل لقاء إضافي.",
      "راجع Starts وEnds وTimezone وAttendance وLocation لكل Occurrence على حدة.",
      "استخدم Status = Cancelled فقط للقاء الملغي، وليس لإخفاء البرنامج كله.",
      "احفظ Create draft وراجع ترتيب كل المواعيد.",
      "Publish ثم تأكد من Calendar sync لكل Occurrence ومن روابط Meet المطلوبة.",
    ],
    impact: ["حجز واحد يستهلك مقعدًا واحدًا من Program capacity ويشمل كل اللقاءات.", "كل Occurrence تملك وقتها ومكانها وحالة مزامنتها.", "إلغاء Occurrence لا يساوي أرشفة Program بالكامل."],
    mistakes: ["إنشاء Program منفصلة لكل لقاء يفصل التسجيلات ويكرر الدفع.", "نسيان Occurrence يؤدي إلى جدول ناقص للعميل.", "اختلاف Timezone بين اللقاءات دون قصد يغير وقت العرض."],
    rollback: ["يمكن حذف Occurrence من Draft قبل النشر.", "بعد النشر، وثّق التعديل وتابع Calendar sync وإشعار العملاء.", "استخدم Retry calendar sync إذا فشل تحديث التقويم."],
  }),
  playbook({
    id: "split-weekday-availability",
    title: "إضافة فترتين للحجز في اليوم نفسه",
    summary: "إنشاء نافذتين منفصلتين لنفس Offering واليوم؛ مثل 09:00–13:00 ثم 14:00–22:00.",
    aliases: ["availability", "slot", "window", "weekday", "فترتين", "مواعيد", "إتاحة"],
    href: "/admin/availability",
    when: ["عندما توجد راحة أو فترة مغلقة داخل اليوم ولا تريد ظهور Slots خلالها."],
    before: ["تأكد أن Offering بنظام Appointment slots.", "حدد Duration وBuffers من Offering لأن نافذة الإتاحة لا تستبدلها."],
    steps: [
      "في Availability اختر Offering واليوم وابدأ بالنافذة الأولى، مثل 09:00 إلى 13:00.",
      "اختر Published واضغط Add window.",
      "أضف نافذة ثانية لنفس Offering واليوم، مثل 14:00 إلى 22:00.",
      "تأكد أن End الأولى قبل Start الثانية ولا يوجد تداخل.",
      "راجع Calendar overview وصفحة الحجز وتأكد من ترتيب Slots زمنيًا.",
    ],
    impact: ["Slots تُولد داخل كل نافذة باستخدام Duration وBuffers من Offering.", "الفجوة بين النافذتين تظل غير قابلة للحجز.", "الحد الأدنى للحجز المسبق وDate overrides يطبقان فوق هذه النوافذ."],
    mistakes: ["تداخل نافذتين قد يسبب رفض الحفظ أو نتائج مربكة.", "استخدام Weekday خاطئ بسبب افتراض ترقيم الأيام بدل قراءة الاسم الظاهر.", "تعديل Duration في Offering يغير توزيع Slots في كل النوافذ التابعة."],
    rollback: ["استخدم Edit لتصحيح Start أوEnd.", "استخدم Delete إذا كانت النافذة غير مستخدمة ويسمح النظام، وإلا Archive.", "لا تؤرشف كل اليوم إذا كان المطلوب حذف نافذة واحدة فقط."],
  }),
  playbook({
    id: "date-overrides",
    title: "إغلاق أو فتح تاريخ استثنائي",
    summary: "استخدام Date overrides لتغيير يوم محدد بدون تعديل الجدول الأسبوعي الدائم.",
    aliases: ["availability", "overrides", "closed", "open", "إجازة", "إغلاق يوم", "استثناء"],
    href: "/admin/availability",
    when: ["للإجازات أو السفر أو فتح ساعات استثنائية في تاريخ واحد فقط."],
    before: ["حدد Offering والتاريخ المقصودين بدقة.", "لا تعدّل Weekly window إذا كان التغيير ليوم واحد."],
    steps: [
      "افتح Date overrides داخل Availability.",
      "اختر Offering والتاريخ.",
      "أنشئ Override مغلقًا لإلغاء إتاحة ذلك التاريخ، أو مفتوحًا بالساعات المطلوبة إذا كانت الواجهة تسمح بذلك.",
      "احفظ ثم راجع Calendar overview.",
      "اختبر التاريخ نفسه في صفحة الحجز ولا تكتفِ بمراجعة اليوم الأسبوعي.",
    ],
    impact: ["الـOverride له أولوية على الجدول الأسبوعي في التاريخ المحدد.", "لا يغيّر بقية الأسابيع أو نفس يوم الأسبوع في تواريخ أخرى."],
    mistakes: ["إغلاق Weekday كامل بدل تاريخ واحد.", "اختبار شهر أو Timezone غير المقصودين.", "نسيان إزالة Override مؤقت بعد تغير الخطة."],
    rollback: ["عدّل أو احذف/أرشف Override حسب الأوامر المتاحة.", "تأكد بعد التراجع أن Weekly availability الأصلية عادت للظهور."],
  }),
  playbook({
    id: "minimum-advance-days",
    title: "التحكم في الحجز المسبق عالميًا",
    summary: "إغلاق تواريخ كاملة قبل أول تاريخ مسموح للحجز لكل Appointments وPrograms.",
    aliases: ["availability", "booking policy", "minimum advance booking days", "earliest bookable date", "حجز مسبق", "يومين"],
    href: "/admin/availability",
    when: ["عندما لا تريد أن يحجز العميل اليوم أو خلال عدد محدد من الأيام القادمة."],
    before: ["اختر Booking timezone الصحيحة؛ الحساب مبني على التاريخ الكامل داخلها.", "القيمة من 1 إلى 365 يومًا."],
    steps: [
      "افتح Booking policy في Availability.",
      "اكتب Minimum advance booking days؛ مثال 1 يعني أن اليوم مغلق وأول حجز من الغد.",
      "اكتب Booking timezone مثل Africa/Cairo.",
      "اقرأ المعاينة التي تعرض Today وEarliest date قبل الحفظ.",
      "اضغط Save policy واختبر التقويم كعميل.",
    ],
    impact: ["القاعدة Global وتغلق تواريخ كاملة لكل Appointment وProgram.", "الحجز القديم الذي تم إنشاؤه قبل تغيير السياسة يظل قائمًا.", "القيمة 2 تغلق اليوم وغدًا، ويبدأ الحجز من اليوم التالي لهما."],
    mistakes: ["اعتبار القيمة ساعات من اللحظة الحالية؛ هي أيام تقويم كاملة.", "تغيير Timezone بدون فهم قد يغير معنى اليوم الحالي قرب منتصف الليل.", "توقع إلغاء الحجوزات الموجودة؛ السياسة تمنع حجوزات جديدة فقط."],
    rollback: ["أعد القيمة إلى العدد السابق واحفظ.", "لا يمكن وضع 0 في السلوك الحالي؛ الحد الأدنى يوم واحد."],
  }),
  playbook({
    id: "attendance-and-locations",
    title: "إعداد Online وOffline وHybrid وLocation",
    summary: "تحديد طريقة الحضور ومتى يصبح المكان مطلوبًا.",
    aliases: ["locations", "attendance", "online", "offline", "hybrid", "location", "مكان", "أونلاين"],
    href: "/admin/locations",
    when: ["لكل خدمة أو Session أو Program يجب أن يعرف العميل هل الحضور أونلاين أم في مكان فعلي."],
    before: ["جهز اسم المكان والعنوان والمدينة والتعليمات إذا كان الحضور فعليًا."],
    steps: [
      "أنشئ Location من صفحة Locations واجعلها فعالة.",
      "في Offering اختر Attendance = Online أو Offline أو Hybrid.",
      "في Session أو Program اختر Mode المتوافق.",
      "اختر Location لكل موعد Offline أو Hybrid.",
      "للـOnline، راجع Integrations إذا كنت تعتمد Google Meet.",
      "اختبر تفاصيل الحجز والرسالة المرسلة للعميل.",
    ],
    impact: ["Offline وHybrid يحتاجان Location في التدفقات التي تفرض المكان.", "Online قد يعتمد على Calendar/Meet لإنشاء رابط الاجتماع.", "Hybrid يسمح بتحديد نمط الموعد أو الـOccurrence وفق قيود Offering."],
    mistakes: ["أرشفة Location ما زالت مستخدمة في موعد قادم.", "اختيار Offline وترك المكان فارغًا.", "وضع رابط الاجتماع في حقول المكان بدل الاعتماد على التكامل."],
    rollback: ["عدّل Location نفسها إذا تغيرت تفاصيل المكان لكل الاستخدامات المقصودة.", "أنشئ Location جديدة إذا كان التغيير لا يجب أن يؤثر على مواعيد قديمة."],
  }),
  playbook({
    id: "capacity",
    title: "فهم وضبط Capacity",
    summary: "Capacity هي الحد الأقصى للمقاعد، لكن نطاقها يختلف بين Offering وSession وProgram.",
    aliases: ["capacity", "booked", "held", "remaining", "سعة", "مقاعد", "عدد العملاء"],
    href: "/admin/offerings",
    when: ["عند تحديد هل الموعد فردي أم جماعي أو عند فتح مقاعد إضافية."],
    before: ["حدد هل تعدّل القيمة الافتراضية في Offering أم موعدًا ثابتًا أم Program كاملًا.", "راجع Booked وHeld قبل تقليل السعة."],
    steps: [
      "في Offering اضبط Capacity الافتراضية؛ 1 تعني موعدًا فرديًا عادة.",
      "في Sessions اضبط Capacity الخاصة بالموعد الثابت نفسه.",
      "في Program استخدم Enrollment capacity للبرنامج الكامل بكل Occurrences.",
      "راقب Total وBooked وHeld وLeft في البرامج.",
      "اختبر محاولة الحجز بعد امتلاء السعة للتأكد من السلوك المتوقع.",
    ],
    impact: ["رفع السعة يسمح بحجوزات إضافية إذا لم توجد قيود أخرى.", "خفض السعة تحت الإشغال الحالي لا يلغي حجوزات موجودة تلقائيًا.", "Held قد تجعل Remaining صفرًا حتى انتهاء المهلة أو اكتمال الدفع."],
    mistakes: ["افتراض أن تغيير Offering يعيد كتابة Sessions أو Programs موجودة.", "خفض السعة بدون مراجعة الحجوزات.", "حساب Booked فقط وتجاهل Held."],
    rollback: ["أعد القيمة السابقة إذا لم تدخل حجوزات جديدة في الفترة بين التعديلين.", "إذا حدث Overbooking، لا تحذف حجوزات عشوائيًا؛ راجع Bookings وتواصل مع المتأثرين."],
  }),
  playbook({
    id: "booking-modes",
    title: "اختيار Free أو Paid أو Quote only",
    summary: "Booking mode يحدد هل الحجز يتأكد مباشرة أم يحتاج دفعًا أم يتحول لطلب عرض سعر.",
    aliases: ["offerings", "free", "paid", "quote only", "booking mode", "مجاني", "مدفوع", "عرض سعر"],
    href: "/admin/offerings",
    when: ["عند تحديد مسار العميل التجاري لكل Offering."],
    before: ["جهز السعر والتكاملات المطلوبة قبل اختيار Paid.", "حدد عملية متابعة واضحة قبل اختيار Quote only."],
    steps: [
      "افتح Offering وحدد Booking mode.",
      "اختر Free للحجز بدون Checkout مدفوع.",
      "اختر Paid عندما يجب الدفع قبل التأكيد وفق التدفق الحالي.",
      "اختر Quote only عندما تريد جمع بيانات العميل ثم التسعير والمتابعة يدويًا.",
      "راجع Requires payment وQuote only الظاهرين في النموذج ولا تترك قيمًا متعارضة.",
      "احفظ واختبر رحلة العميل كاملة حتى النهاية.",
    ],
    impact: ["Free يقلل خطوات الحجز.", "Paid ينشئ سجل دفع ويؤثر في تأكيد الحجز.", "Quote only يرسل الطلب إلى Quotes بدل إكمال حجز مدفوع مباشر."],
    mistakes: ["نشر Paid بلا سعر صالح أو بوابة جاهزة.", "اعتبار Quote طلب حجز مؤكد.", "تغيير Booking mode أثناء وجود حملات أو عملاء داخل التدفق دون اختبار."],
    rollback: ["أعد Booking mode السابقة واختبر طلبًا جديدًا.", "لا تفترض أن السجلات القديمة ستتحول تلقائيًا إلى المسار الجديد."],
  }),
  playbook({
    id: "pricing",
    title: "الأسعار وPrice groups وEarly bird",
    summary: "ضبط Base amount والأسعار حسب البلد والعروض المبكرة بدون تغيير الخدمة نفسها.",
    aliases: ["offerings", "base amount", "price groups", "early bird", "currency", "country", "ip", "سعر", "عملة", "عرض مبكر"],
    href: "/admin/offerings",
    when: ["للخدمات Paid أو عند عرض أسعار مختلفة حسب بلد العميل أو توقيت التسجيل."],
    before: ["احفظ Offering أولًا حتى يظهر جزء Price groups.", "حدد العملة والوحدة بدقة؛ المبلغ يُخزن ويُعرض وفق عقد التسعير الحالي."],
    steps: [
      "افتح Edit للـOffering ثم قسم Price groups.",
      "أدخل Base amount كسعر أساسي عندما لا ينطبق Group أكثر تحديدًا.",
      "أنشئ Price group بالعملة والمبلغ والدول المقصودة.",
      "حدد Early bird amount وموعد النهاية فقط إذا كان هناك خصم تسجيل مبكر حقيقي.",
      "تأكد أن نطاقات الدول لا تتعارض وأن هناك Fallback مفهومًا.",
      "اختبر السعر من رحلة العميل وراجع البلد الذي اختاره النظام تلقائيًا.",
    ],
    impact: ["العميل يرى السعر المطابق لمجموعة بلده عند نجاح التحديد، وإلا يستخدم المسار الاحتياطي الحالي.", "Early bird يطبق داخل نافذته الزمنية فقط.", "تغيير السعر يؤثر على الطلبات الجديدة ولا يعيد تسعير مدفوعات مكتملة تلقائيًا."],
    mistakes: ["اعتبار Base amount عدد جلسات؛ هو قيمة السعر الأساسية.", "وضع Early bird بلا تاريخ نهاية واضح.", "الاعتماد على تحديد البلد دون اختبار Fallback أو استخدام VPN/شبكات مختلفة.", "تغيير العملة مع الإبقاء على قيمة رقمية قديمة غير مناسبة."],
    rollback: ["أعد Price group أو Base amount السابقة للطلبات الجديدة.", "أوقف Early bird بانتهاء النافذة أو تعديلها بدل حذف تاريخ المبيعات.", "راجع Payments إذا تم إنشاء طلب بسعر غير صحيح قبل التراجع."],
  }),
  playbook({
    id: "booking-operations",
    title: "مراجعة الحجوزات والتعامل معها",
    summary: "فهم سجل العميل وحالة الحجز والموعد والدفع قبل اتخاذ إجراء.",
    aliases: ["bookings", "booking", "confirmed", "cancel", "reschedule", "حجوزات", "إلغاء"],
    href: "/admin/bookings",
    when: ["عند متابعة حجز جديد أو الرد على عميل أو التحقق من حالة الموعد."],
    before: ["ابحث بالعميل أو الخدمة أو الحالة الصحيحة.", "راجع الدفع والموعد قبل أي إلغاء أو تعديل."],
    steps: [
      "افتح Bookings واستخدم الفلاتر للوصول إلى السجل.",
      "افتح تفاصيل الحجز وراجع Customer وOffering والموعد وTimezone وStatus.",
      "راجع Payment أو Quote المرتبط إذا كان المسار Paid أو Quote only.",
      "نفّذ الإجراء المتاح فقط بعد فهم أثره على السعة والتقويم والإيميل.",
      "سجل المتابعة التشغيلية خارج الداشبورد إذا لم يوجد حقل مخصص لها.",
    ],
    impact: ["تغيير حالة الحجز قد يحرر أو يشغل السعة حسب قواعد النظام.", "بعض الإجراءات قد تفعّل رسائل أو مزامنة خلفية."],
    mistakes: ["إلغاء سجل العميل الخطأ بسبب فلتر واسع.", "اعتبار Payment ناجحًا من حالة Booking فقط.", "تعديل Session الأساسية لحل مشكلة عميل واحد فيؤثر على بقية العملاء."],
    rollback: ["لا تفترض أن كل حالة قابلة للعكس؛ اقرأ الأوامر المتاحة.", "إذا كان الإجراء غير قابل للتراجع، تواصل مع العميل وأنشئ التصحيح التشغيلي المناسب بدل العبث بالسجل."],
  }),
  playbook({
    id: "payment-operations",
    title: "مراجعة Payments والحالات المعلقة",
    summary: "تمييز حالة الدفع عن حالة الحجز واستخدام إعادة المعالجة المتاحة بأمان.",
    aliases: ["payments", "payment", "pending", "failed", "reconcile", "دفع", "معلق", "فشل"],
    href: "/admin/payments",
    when: ["عندما يقول العميل إنه دفع أو عندما لا يتطابق الحجز مع حالة عملية الدفع."],
    before: ["جهز اسم العميل وBooking reference وPayment reference إن وجد.", "لا تكرر الخصم يدويًا من لوحة غير مخصصة لذلك."],
    steps: [
      "افتح Payments وابحث عن السجل الصحيح.",
      "راجع Amount وCurrency وProvider status والحالة الداخلية والتوقيت.",
      "افتح الحجز المرتبط وقارن الحالتين.",
      "استخدم Retry أوReconcile فقط إذا كان الزر متاحًا والحالة مناسبة.",
      "حدّث الصفحة وتحقق من النتيجة بدل تكرار الضغط فورًا.",
    ],
    impact: ["نجاح المصالحة قد يحدّث الحجز أو يطلق معالجة لاحقة.", "فشل الدفع لا يعني دائمًا حذف Booking؛ قد يبقى في حالة انتظار أو فشل."],
    mistakes: ["الضغط المتكرر على Retry قبل ظهور نتيجة المحاولة الأولى.", "مطابقة السجل بالاسم فقط بدل Reference والمبلغ.", "اعتبار سجل الداشبورد بديلًا عن إثبات Provider عند النزاع المالي."],
    rollback: ["الإجراءات المالية ليست كلها قابلة للعكس من الداشبورد.", "إذا بقي التعارض بعد Reconcile واحدة، احتفظ بالمراجع وراجع بوابة الدفع بدل إنشاء تعديل عشوائي."],
  }),
  playbook({
    id: "quote-operations",
    title: "متابعة Quote requests",
    summary: "مراجعة طلبات الخدمات Quote only والتواصل مع العميل بدون اعتبارها حجوزات مؤكدة.",
    aliases: ["quotes", "quote", "inquiry", "عرض سعر", "طلب مخصص"],
    href: "/admin/quotes",
    when: ["للخدمات التي تحتاج تسعيرًا أو نطاقًا مخصصًا قبل الحجز."],
    before: ["تأكد أن Offering مضبوطة على Quote only.", "جهز معايير التأهيل والأسئلة المطلوبة."],
    steps: [
      "افتح Quotes واستخدم البحث والفلاتر.",
      "افتح الطلب وراجع بيانات العميل والخدمة والإجابات.",
      "غيّر الحالة المتاحة بما يعكس مرحلة المتابعة الفعلية.",
      "تواصل مع العميل عبر القناة المتفق عليها وأرسل العرض.",
      "لا تعتبر الطلب Booking إلا بعد إكمال المسار الذي يؤكد الحجز فعليًا.",
    ],
    impact: ["الحالة تساعد الفريق في معرفة الطلبات الجديدة والمتابعة.", "Quote لا يشغل Slot أوCapacity كحجز مؤكد إلا إذا كان الكود ينشئ حجزًا لاحقًا."],
    mistakes: ["ترك الطلبات بلا تحديث حالة.", "وعد العميل بموعد قبل التحقق من Availability أوProgram capacity.", "خلط Quotes مع Payments."],
    rollback: ["صحح الحالة إذا تم اختيارها بالخطأ.", "لا تحذف الطلب التاريخي إذا كان Archive متاحًا ويكفي للغرض."],
  }),
  playbook({
    id: "booking-form-fields",
    title: "تعديل أسئلة نموذج الحجز",
    summary: "إضافة الأسئلة التي يحتاجها التشغيل فقط وترتيبها ونشرها.",
    aliases: ["form-fields", "form fields", "questions", "required", "أسئلة الحجز", "نموذج"],
    href: "/admin/form-fields",
    when: ["عندما تحتاج بيانات إضافية من العميل قبل إكمال الحجز."],
    before: ["حدد هل السؤال مطلوب فعلًا وهل الإجابة ستُستخدم تشغيليًا.", "تجنب طلب بيانات حساسة بلا ضرورة."],
    steps: [
      "افتح Form Fields وأنشئ Field جديدة.",
      "اختر Label وField type وخيارات الإجابة إن كانت مطلوبة.",
      "حدد Required فقط إذا كان الحجز لا يمكن تشغيله بدون الإجابة.",
      "اضبط Sort order وحالة النشر.",
      "احفظ واختبر النموذج العام على سطح المكتب والموبايل.",
    ],
    impact: ["Published fields تظهر في نموذج العميل حسب ترتيبها وقواعدها.", "Required تمنع المتابعة حتى إدخال إجابة صالحة."],
    mistakes: ["تكرار سؤال موجود.", "جعل كل شيء Required فيرفع ترك الحجز.", "أرشفة Field قبل التأكد من أثرها على عرض إجابات الحجوزات القديمة."],
    rollback: ["ارجع Field إلى Draft أوArchive حسب الحالة المتاحة.", "لا تغير معنى السؤال القديم جذريًا؛ أنشئ سؤالًا جديدًا إذا كانت الإجابات القديمة يجب أن تحتفظ بمعناها."],
  }),
  playbook({
    id: "email-operations",
    title: "متابعة Emails وإعادة الإرسال",
    summary: "فحص التسليم والقالب والسبب قبل إعادة محاولة رسالة فاشلة.",
    aliases: ["emails", "email", "template", "delivery", "retry", "إيميل", "رسالة"],
    href: "/admin/emails",
    when: ["عندما لا تصل رسالة للعميل أو عند تعديل قالب الرسائل."],
    before: ["تحقق من عنوان البريد ووقت الإرسال ونوع الرسالة.", "لا تعاود الإرسال عدة مرات قبل معرفة الحالة."],
    steps: [
      "افتح Emails وابحث عن Delivery بالعميل أو النوع أو الحالة.",
      "راجع الخطأ وProvider reference إن ظهر.",
      "صحح Template إذا كان الخطأ في المحتوى أو المتغيرات.",
      "استخدم Retry للرسالة المناسبة مرة واحدة.",
      "حدّث القائمة وتأكد من Delivered أوالحالة النهائية.",
    ],
    impact: ["تعديل Template يؤثر على الرسائل الجديدة التي تستخدمه.", "Retry يعيد محاولة Delivery المحددة ولا يغير عنوان عميل خاطئ داخل سجل آخر تلقائيًا."],
    mistakes: ["إعادة عدة رسائل مكررة للعميل.", "تعديل قالب Published بدون مراجعة القيم الديناميكية.", "افتراض أن عدم رؤية الرسالة يعني فشل الإرسال قبل فحص Spam والحالة."],
    rollback: ["أعد محتوى القالب السابق إذا كان التعديل الجديد خاطئًا.", "إذا وصلت رسالة مكررة فلا تعاود Retry؛ صحح العملية التالية فقط."],
  }),
  playbook({
    id: "create-cms-page",
    title: "إنشاء صفحة جديدة وإضافة Sections",
    summary: "إنشاء Page ثم تركيبها من السيكشنات الجاهزة ومعاينتها قبل النشر.",
    aliases: ["cms", "pages", "sections", "slug", "new page", "صفحة", "سيكشن"],
    href: "/admin/cms",
    when: ["عندما تحتاج صفحة محتوى جديدة مبنية من أنواع السيكشنات المدعومة."],
    before: ["حدد عنوانًا وSlug غير مستخدمين.", "جهز النصوص والوسائط والروابط المطلوبة."],
    steps: [
      "افتح CMS ثم Pages واضغط New page.",
      "أدخل Page title وSlug واجعل Status = Draft.",
      "اضغط Create page ثم اختر نوع Section جاهز وأضفه.",
      "املأ حقول Section واربط الصور أوالفيديوهات المطلوبة.",
      "احفظ كل Section ورتب السيكشنات بالترتيب المطلوب.",
      "استخدم Open preview وراجع الصفحة كاملة.",
      "اضبط SEO ثم غيّر الصفحة إلى Published أوScheduled مع وقت صالح.",
    ],
    impact: ["Slug يحدد رابط الصفحة.", "Status الصفحة والسيكشنات يحددان ما يمكن نشره.", "ترتيب Sections يغيّر ترتيب العرض العام."],
    mistakes: ["نشر الصفحة مع Section ناقصة أوDraft.", "تغيير Slug بعد مشاركة الرابط.", "إنشاء Section من نوع لا يطابق المحتوى ثم محاولة إجبار التصميم عليه."],
    rollback: ["ارجع الصفحة أوالسيكشن إلى Draft للتصحيح.", "استخدم Archive بدل الحذف عندما نُشرت الصفحة أوارتبطت بها روابط.", "استخدم Preview قبل إعادة النشر."],
  }),
  playbook({
    id: "edit-section-media",
    title: "تعديل نص أوصورة أوفيديو داخل Section",
    summary: "تغيير محتوى السيكشن وربط الوسائط الصحيحة ثم حفظه ونشر الصفحة.",
    aliases: ["cms", "section", "image", "video", "replace", "صورة", "فيديو", "تعديل سيكشن"],
    href: "/admin/cms",
    when: ["عند تحديث جزء موجود في صفحة بدون إنشاء صفحة جديدة."],
    before: ["اختر الصفحة والسيكشن الصحيحين.", "جهز Alt text للصورة ومعاينة مناسبة للفيديو."],
    steps: [
      "افتح CMS ثم Pages واختر الصفحة والسيكشن.",
      "عدّل النص أوالرابط في الحقول الظاهرة لنوع Section.",
      "استخدم Replace/Choose from library لاختيار ملف موجود، أوUpload from device لفتح ملفات جهازك مباشرة، أوExternal URL لرابط موثوق.",
      "تأكد أن المعاينة تعرض الأصل الصحيح وأن Processing state = Ready عند الحاجة.",
      "اضغط Save section ثم Open preview.",
      "راجع الصفحة العامة بعد النشر وتحقق من الكاش قبل اعتبار التعديل مفقودًا.",
    ],
    impact: ["Save section يحفظ نسخة السيكشن الحالية، بينما ظهورها العام يعتمد أيضًا على حالة الصفحة والنشر.", "Replace يغير ارتباط هذا الموضع ولا يحذف Asset من المكتبة."],
    mistakes: ["رفع ملف ثم عدم الضغط على Upload selected file.", "اختيار Asset من المكتبة ثم نسيان Save section.", "حذف Asset مستخدمة في أكثر من مكان بدل استبدالها في الموضع المقصود."],
    rollback: ["اختر Asset السابقة من Media Library واحفظ السيكشن.", "أعد النص السابق ثم Preview قبل النشر.", "لا تحذف الملف القديم نهائيًا حتى تتأكد أنه غير مستخدم."],
  }),
  playbook({
    id: "media-library",
    title: "استخدام Media Library ورفع الملفات",
    summary: "رفع صورة أوفيديو إلى R2، إضافة رابط خارجي، وفهم Ready وProcessing وFailed.",
    aliases: ["cms", "media", "upload from device", "external url", "r2", "processing", "مكتبة", "رفع ملف"],
    href: "/admin/cms",
    when: ["لإضافة أصل بصري جديد أوإعادة استخدام ملف مرفوع من قبل."],
    before: ["استخدم نوع وحجم ملف مناسبين للحقل.", "اكتب اسمًا واضحًا وAlt text للصور المحتوائية."],
    steps: [
      "من CMS > Media افتح Add media.",
      "اضغط Upload from device واختر الملف من جهازك.",
      "بعد ظهور اسم الملف اضغط Upload selected file وانتظر Signing ثمUploading ثمChecking file.",
      "استخدم Choose from library لإعادة استخدام Asset موجودة بدل رفع نسخة مكررة.",
      "استخدم External URL فقط لرابط HTTPS ثابت ومتاح للعامة، ثم تحقق من المعاينة.",
      "افتح تفاصيل Asset لتعديل Display name وAlternative text ومراجعة Used in.",
    ],
    impact: ["الرفع المباشر يخزن الملف في R2 ثم يسجل Asset داخل CMS.", "Animation bundles قد تحتاج Processing قبل الاختيار.", "Archive يمنع الاستخدام الجديد، وDelete permanently لا يكون آمنًا إلا بعد الأرشفة وعدم وجود Usages."],
    mistakes: ["إغلاق الصفحة أثناء الرفع.", "استخدام رابط خارجي مؤقت أوخاص.", "رفع نفس الملف عدة مرات بدل اختياره من المكتبة.", "حذف Asset قبل مراجعة Used in."],
    rollback: ["استبدل الارتباط في السيكشن أولًا.", "Archive الملف غير المستخدم، ثم احذفه نهائيًا فقط إذا كانت Usages صفرًا وكان الحذف مطلوبًا."],
  }),
  playbook({
    id: "legal-pages",
    title: "إنشاء وتحديث الصفحات القانونية",
    summary: "إدارة نسخة قانونية واضحة مع Slug وVersion وحالة نشر وتاريخ صالح.",
    aliases: ["cms", "legal", "privacy", "terms", "version", "قانونية", "خصوصية", "شروط"],
    href: "/admin/cms",
    when: ["لصفحات Privacy Policy أوTerms أوأي وثيقة قانونية منشورة."],
    before: ["احصل على النص القانوني المعتمد.", "حدد Version جديدة عند تغيير جوهري بدل طمس تاريخ النسخ."],
    steps: [
      "افتح CMS > Legal واضغط New legal page.",
      "أدخل Title وSlug وVersion.",
      "اكتب Body بصيغة Markdown وراجع التنسيق.",
      "احفظ كـDraft للمراجعة.",
      "اختر Published للنشر الآن أوScheduled وحدد Published at صالحًا.",
      "افتح الرابط العام وتأكد من النص الكامل وروابط Navigation/Footer.",
    ],
    impact: ["Slug يحدد رابط الوثيقة.", "Version توضح النسخة القانونية الحالية.", "Scheduled لا يعمل كما تقصد إذا لم يُحدد وقت نشر صحيح."],
    mistakes: ["تعديل وثيقة منشورة جوهريًا بدون رفع Version.", "نشر Markdown غير مراجع.", "أرشفة صفحة ما زال Footer يشير إليها."],
    rollback: ["ارجع إلى Draft قبل النشر إذا اكتشفت خطأ.", "للتغييرات القانونية الكبيرة أنشئ/احفظ النسخة الصحيحة بدل حذف التاريخ بلا مراجعة."],
  }),
  playbook({
    id: "blog-and-seo",
    title: "إنشاء Blog post وضبط الصورة وSEO",
    summary: "إدارة المقال والتصنيف والصورة البارزة وبيانات محركات البحث حتى النشر.",
    aliases: ["cms", "blog", "seo", "featured image", "category", "meta title", "مقال", "تصنيف"],
    href: "/admin/cms",
    when: ["عند نشر محتوى مقالي يحتاج رابطًا وصورة وبيانات SEO مستقلة."],
    before: ["جهز Title وSlug ومحتوى Markdown وصورة أفقية مناسبة وMeta description."],
    steps: [
      "افتح CMS > Blog وأنشئ Category إذا لم تكن موجودة.",
      "أنشئ Post وأدخل Title وSlug وExcerpt وBody.",
      "اختر Category والصورة البارزة من MediaPicker.",
      "احفظ Draft ثم افتح SEO fields.",
      "اكتب Meta title وMeta description وCanonical عند الحاجة، واختر Social image.",
      "راجع المعاينة ثم انشر أوحدد موعد النشر.",
    ],
    impact: ["Slug يحدد رابط المقال.", "Featured image تظهر داخل تجربة المقال حسب القالب.", "SEO metadata تؤثر في عنوان ووصف المشاركة والبحث، وليست بديلًا عن محتوى جيد."],
    mistakes: ["Slug مكرر أوتغييره بعد الأرشفة في محركات البحث.", "صورة بلا Alt text.", "Meta title طويل أوDescription غير مرتبطة بالمقال.", "نشر Post بلا Category أوBody مكتمل."],
    rollback: ["ارجع Status إلى Draft وصحح المحتوى.", "استبدل الصورة من المكتبة بدل حذف Asset مستخدمة.", "إذا تغير الرابط، خطط للـredirect خارج نطاق هذه الصفحة بدل كسر الرابط بصمت."],
  }),
  playbook({
    id: "navigation",
    title: "تعديل روابط Header وFooter",
    summary: "إضافة رابط وتحديد مكانه وترتيبه وحالته بدون كسر التنقل.",
    aliases: ["cms", "navigation", "header", "footer", "sort order", "روابط", "القائمة"],
    href: "/admin/cms",
    when: ["عند إضافة صفحة للقائمة أوتغيير ترتيب الروابط العامة."],
    before: ["تأكد أن URL موجود ويعمل.", "حدد هل الرابط Header أمFooter والترتيب المطلوب."],
    steps: [
      "افتح CMS > Navigation واضغط New link.",
      "أدخل Label وURL.",
      "حدد Location بالقيمة المستخدمة حاليًا مثل header أوfooter.",
      "حدد Sort order؛ الرقم الأقل يظهر قبل الأكبر داخل نفس المكان.",
      "احفظ كـDraft للاختبار ثم Published عند الجاهزية.",
      "راجع القائمة العامة على Desktop وMobile.",
    ],
    impact: ["Published links تظهر في المكان المحدد.", "Sort order يغير ترتيب الروابط داخل Location نفسها."],
    mistakes: ["كتابة URL داخلي بلا / في البداية.", "نشر رابط لصفحة Draft أوArchived.", "استخدام Location غير معروفة في القالب."],
    rollback: ["ارجع الرابط إلى Draft أوArchive.", "صحح Sort order بدل حذف الروابط وإعادة إنشائها."],
  }),
  playbook({
    id: "site-settings",
    title: "تعديل بيانات التواصل وروابط السوشيال",
    summary: "تحديث Site name وContact email وPhone وروابط الشبكات المستخدمة في الموقع.",
    aliases: ["cms", "settings", "site name", "contact email", "phone", "instagram", "linkedin", "youtube", "تواصل", "سوشيال"],
    href: "/admin/cms",
    when: ["عند تغيير بيانات العلامة أووسائل التواصل الحالية."],
    before: ["جهز القيم النهائية واختبر كل رابط HTTPS."],
    steps: [
      "افتح CMS > Settings داخل CMS، وليس عنصر Settings المعطل في القائمة العامة.",
      "راجع Site name وDefault locale.",
      "حدّث Contact email وContact phone.",
      "حدّث Instagram وLinkedIn وYouTube بروابط كاملة.",
      "اضغط Save settings ثم راجع المواضع العامة التي تعرض البيانات.",
    ],
    impact: ["البيانات المحفوظة قد تظهر في أكثر من موضع عام.", "الرابط الخاطئ يؤثر على كل زر يستخدم إعداد الشبكة نفسها."],
    mistakes: ["إدخال اسم مستخدم فقط بدل URL كامل.", "تغيير Default locale بلا مراجعة أثر اللغة.", "افتراض أن Settings العامة المعطلة متاحة؛ الإعدادات الحالية داخل CMS فقط."],
    rollback: ["أعد القيمة السابقة واضغط Save settings.", "اختبر الروابط بعد كل تغيير بدل انتظار شكوى المستخدم."],
  }),
  playbook({
    id: "calendar-meet",
    title: "إعداد Google Calendar وMeet ومعالجة فشل Sync",
    summary: "ربط التكامل ومراقبة الأحداث والروابط وإعادة المزامنة عند الحاجة.",
    aliases: ["integrations", "google calendar", "google meet", "calendar sync", "retry", "تقويم", "ميت"],
    href: "/admin/integrations",
    when: ["لإنشاء أحداث التقويم وروابط Meet تلقائيًا للمواعيد المدعومة."],
    before: ["تأكد أن حساب Google الصحيح متصل وأنه يملك صلاحية التقويم المقصود.", "راجع Timezone قبل إنشاء المواعيد."],
    steps: [
      "افتح Integrations وراجع حالة Calendar and Meet.",
      "أكمل الاتصال أوالإعدادات المطلوبة في الواجهة.",
      "أنشئ/انشر Session أوProgram تجريبيًا.",
      "راجع Calendar event id وMeet URL وحالة Sync.",
      "إذا فشل Sync، صحح سبب الاتصال ثم استخدم Retry calendar sync مرة واحدة.",
      "تحقق من الحدث داخل Google Calendar ومن وقت الدعوة الفعلي.",
    ],
    impact: ["النشر أوالحجز قد يطلق Jobs للمزامنة في الخلفية.", "فشل Calendar لا يعني بالضرورة فشل حفظ Program نفسها؛ راجع الحالتين منفصلتين."],
    mistakes: ["إعادة Retry قبل إصلاح الاتصال.", "تعديل الحدث يدويًا في Google ثم توقع أن كل تغييرات الداشبورد تندمج بلا تعارض.", "إهمال Timezone."],
    rollback: ["أعد الاتصال الصحيح ثم Retry.", "لا تنشئ Program مكررة فقط لأن Calendar event لم يظهر؛ أصلح المزامنة للسجل الأصلي."],
  }),
  playbook({
    id: "preview-and-publish",
    title: "المعاينة والاختبار قبل النشر",
    summary: "قائمة مراجعة قصيرة تمنع نشر صفحة أوخدمة ناقصة للعميل.",
    aliases: ["cms", "preview", "publish", "seo", "test", "معاينة", "اختبار", "نشر"],
    href: "/admin/cms",
    when: ["قبل نشر صفحة أوOffering أوProgram أوتغيير مرئي مهم."],
    before: ["أكمل كل الاعتمادات: محتوى ووسائط وسعر وإتاحة أوOccurrences وتكاملات."],
    steps: [
      "احفظ Draft كاملًا.",
      "استخدم Open preview للـCMS وتحقق من كل Section وروابطها.",
      "اختبر Offering من رحلة عميل جديدة حتى آخر خطوة بدون تنفيذ دفع حقيقي غير مقصود.",
      "راجع Desktop وMobile وTimezone والسعر والبلد.",
      "راجع SEO title وDescription والصورة الاجتماعية للصفحات والمقالات.",
      "انشر ثم افتح الرابط العام في نافذة خاصة وتأكد من النتيجة.",
    ],
    impact: ["Preview لا يساوي Published؛ هو فحص قبل الإتاحة العامة.", "النشر يجعل السجل متاحًا وفق اكتمال بقية الشروط."],
    mistakes: ["اختبار بحساب Admin فقط.", "نسيان Mobile أولغة/بلد مختلف.", "اعتبار حفظ Section نشرًا للصفحة كاملة."],
    rollback: ["أعد الحالة إلى Draft أوArchive حسب السجل.", "صحح ثم أعد الاختبار قبل النشر مرة أخرى."],
  }),
  playbook({
    id: "safe-rollback",
    title: "التعديل الآمن والأرشفة والتراجع",
    summary: "اختيار Draft أوEdit أوArchive أوDelete بناءً على استخدام السجل.",
    aliases: ["archive", "delete", "draft", "rollback", "used in", "أرشفة", "حذف", "تراجع"],
    href: "/admin",
    when: ["قبل إزالة أي خدمة أونافذة أوSession أوProgram أوMedia أوصفحة."],
    before: ["راجع الاستخدامات والحجوزات والتسجيلات والروابط العامة.", "احتفظ بالقيمة القديمة قبل تغيير حرج."],
    steps: [
      "استخدم Draft عندما تريد منع النشر أثناء التجهيز.",
      "استخدم Edit للتصحيح الذي يجب أن يحتفظ بالسجل نفسه.",
      "استخدم Archive عندما توجد علاقات تاريخية أوحجوزات أوUsages.",
      "استخدم Delete فقط عندما تسمح الواجهة وبعد التأكد أن السجل غير مستخدم.",
      "بعد أي تراجع، اختبر رحلة العميل والسجلات المرتبطة.",
    ],
    impact: ["Archive يحافظ على التاريخ ويمنع الاستخدام العادي الجديد.", "Delete قد يكون دائمًا ولا يمكن استعادته.", "تعديل سجل أساسي قد يؤثر على أكثر من صفحة أوحجز جديد."],
    mistakes: ["حذف Asset قبل مراجعة Used in.", "أرشفة Location أوOffering لها مواعيد قادمة.", "تغيير بيانات قديمة لإصلاح حالة جديدة بدل إنشاء سجل مستقل."],
    rollback: ["إذا كان Archive قابلًا للعكس في الواجهة، أعد الحالة المناسبة فقط بعد مراجعة الاعتمادات.", "إذا كان Delete دائمًا، لا توجد استعادة من الدليل؛ تجنب استخدامه بلا ضرورة."],
  }),
];

const pageReferences: GuideEntry[] = [
  reference("overview-reference", "Overview", "نقطة الدخول السريعة لأقسام التشغيل.", ["overview", "admin"], "/admin", ["يعرض روابط مختصرة ووصفًا عامًا للأقسام؛ لا ينشئ بيانات بنفسه."], ["استخدم البطاقات للوصول إلى القسم المقصود."], ["لا تعتمد على Overview لمعرفة كل الحالات؛ افتح الصفحة المتخصصة."],),
  reference("offerings-reference", "Offerings وPricing", "تعريف الخدمات وتصنيفها وجدولتها وحجزها وتسعيرها.", ["offerings", "pricing", "base amount", "early bird", "capacity"], "/admin/offerings", ["تملك تعريف الخدمة الأساسي وحالتها وطريقة الحضور والحجز والجدولة.", "التسعير تابع للـOffering بعد حفظها."], ["Title وSlug وDescriptions وOffering type وStatus.", "Scheduling type: Appointment slots أوScheduled program.", "Attendance وBooking mode وDuration وBuffers وCapacity.", "Display colors وSort order وPrice groups وBase amount وEarly bird."], ["تغيير القيم لا يعني إعادة كتابة Sessions أوPrograms الموجودة.", "راجع الحجوزات قبل تغيير السعة أوالسعر أوالمدة."],),
  reference("availability-reference", "Availability وOverrides وBooking policy", "الجدول الأسبوعي والاستثناءات والتاريخ الأدنى للحجز.", ["availability", "slot", "window", "overrides", "booking policy"], "/admin/availability", ["تملك نوافذ Appointment slots المتكررة والاستثناءات التاريخية والسياسة العالمية للحجز المسبق.", "لا تملك مواعيد Programs؛ هذه تأتي من Occurrences."], ["Offering وWeekday وStart وEnd وStatus.", "Date overrides لإغلاق أوفتح تاريخ خاص.", "Minimum advance booking days وBooking timezone.", "Calendar overview لمراجعة الناتج."], ["Duration وCapacity وBuffers تأتي من Offering.", "تجنب تداخل النوافذ لنفس Offering واليوم."],),
  reference("locations-reference", "Locations", "الأماكن المستخدمة في Offline وHybrid.", ["locations", "location", "venue", "address"], "/admin/locations", ["تملك اسم المكان وعنوانه ومدينته وتفاصيله وحالته."], ["Name وAddress وCity وTimezone أوتعليمات الوصول حسب الحقول الحالية.", "Active/Archived يحدد الاستخدام الجديد."], ["لا تؤرشف مكانًا قبل مراجعة Sessions وPrograms القادمة."],),
  reference("programs-reference", "Events & Programs", "Enrollment واحدة في Event أوWorkshop أوCourse له Occurrences.", ["programs", "events", "occurrences", "course", "workshop"], "/admin/programs", ["تملك Program title وفترة التسجيل والسعة وOccurrences وحالة النشر والمزامنة."], ["Offering يجب أن تكون Scheduled program.", "Registration opens/closes وEnrollment capacity.", "لكل Occurrence: Starts وEnds وTimezone وAttendance وLocation وStatus.", "Publish وRetry calendar sync وArchive/Delete حسب Allowed actions."], ["Registration closes يجب أن يسبق أول Occurrence.", "السعة للبرنامج الكامل وليست لكل لقاء."],),
  reference("form-fields-reference", "Form Fields", "الأسئلة الإضافية في نموذج الحجز.", ["form-fields", "form fields", "questions", "required"], "/admin/form-fields", ["تملك تعريف السؤال ونوعه وإلزامه وترتيبه وحالته."], ["Label وType وOptions وRequired وSort order وStatus."], ["لا تجمع بيانات حساسة أوغير مستخدمة.", "تغيير معنى سؤال قديم يربك تفسير الإجابات السابقة."],),
  reference("sessions-reference", "Sessions", "مواعيد ثابتة مرتبطة بـOffering.", ["sessions", "session", "fixed date", "calendar event id"], "/admin/sessions", ["تملك Starts وEnds وTimezone وMode وLocation وCapacity والحالة لكل Session."], ["Offering وStarts وEnds وMode وCapacity.", "Location مطلوب للحضور الفعلي.", "Calendar event id للتكامل المتقدم فقط.", "Edit وArchive حسب الحالة."], ["لا تستخدم Session بدل Program متعدد اللقاءات.", "راجع الحجوزات قبل تغيير وقت موعد منشور."],),
  reference("bookings-reference", "Bookings", "الحجوزات الفعلية للعملاء وتفاصيلها وحالاتها.", ["bookings", "booking", "customer", "cancel"], "/admin/bookings", ["تعرض العميل والخدمة والموعد والحالة والسعر/الدفع والبيانات المرتبطة."], ["استخدم البحث والفلاتر ثم افتح تفاصيل السجل قبل أي إجراء."], ["لا تعدّل Offering أوSession كاملة لحل مشكلة حجز فردي."],),
  reference("payments-reference", "Payments", "دفتر عمليات الدفع والمصالحة.", ["payments", "payment", "reconcile", "pending", "failed"], "/admin/payments", ["يعرض المبلغ والعملة والمزود والحالات والمراجع والارتباط بالحجز."], ["Filters وDetails وRetry/Reconcile عندما تكون متاحة."], ["لا تكرر الإجراء قبل ظهور نتيجة المحاولة الأولى.", "قارن دائمًا مع Provider reference في النزاعات."],),
  reference("quotes-reference", "Quotes", "طلبات التسعير المخصص للخدمات Quote only.", ["quotes", "quote", "inquiry"], "/admin/quotes", ["تعرض بيانات الطلب والعميل والخدمة والإجابات وحالة المتابعة."], ["Search وFilters وStatus وDetails."], ["Quote ليست Booking مؤكدة ولا Payment."],),
  reference("emails-reference", "Emails", "قوالب الرسائل وسجل التسليم وإعادة المحاولة.", ["emails", "email", "templates", "delivery", "retry"], "/admin/emails", ["تملك قوالب البريد وتعرض Deliveries وحالاتها وأخطاءها."], ["Template content وStatus.", "Delivery details وRetry للفشل المناسب."], ["راجع المتغيرات الديناميكية قبل نشر قالب.", "تجنب إرسال رسائل مكررة."],),
  reference("cms-reference", "CMS: Pages وMedia وLegal وBlog وNavigation وSettings", "إدارة محتوى الموقع والوسائط والصفحات والـSEO.", ["cms", "pages", "media", "global media", "legal", "blog", "navigation", "settings", "seo"], "/admin/cms", ["Pages تركب من Sections جاهزة.", "Media تسجل Assets واستخداماتها.", "Global media للوسائط المشتركة.", "Legal وBlog وNavigation وSite settings تملك محتواها المتخصص."], ["Draft/Published/Scheduled/Archived.", "Upload from device وChoose from library وExternal URL.", "Preview وSEO metadata وSave/Publish حسب كل View."], ["حفظ Section لا ينشر الصفحة تلقائيًا.", "راجع Used in قبل حذف Media.", "Settings العامة في القائمة ما زالت معطلة؛ استخدم Settings داخل CMS فقط."],),
  reference("integrations-reference", "Integrations", "حالة وإعداد Calendar وMeet.", ["integrations", "google calendar", "google meet", "sync"], "/admin/integrations", ["تدير اتصال التكامل الذي تعتمد عليه عمليات التقويم والاجتماعات."], ["Connection/status وإعدادات Calendar and Meet الحالية."], ["فشل التكامل لا يبرر إنشاء Program أوSession مكررة.", "صحح الاتصال ثم Retry من السجل الأصلي."],),
];

const troubleshootingEntries: GuideEntry[] = [
  troubleshooting("offering-not-public", "الخدمة لا تظهر للعميل", ["offering missing", "مش ظاهرة"], "/admin/offerings", ["تأكد أن Offering ليست Draft أوArchived.", "راجع Slug والبيانات المطلوبة.", "إذا كانت Appointment slots فتأكد من Availability منشورة.", "إذا كانت Scheduled program فتأكد من وجود Program منشورة.", "راجع السعر وBooking mode ثم اختبر في نافذة خاصة."]),
  troubleshooting("slots-not-visible", "المواعيد أوSlots لا تظهر", ["availability missing", "slots", "no dates", "مفيش مواعيد"], "/admin/availability", ["تأكد أن Offering = Appointment slots ومنشورة.", "راجع Weekday وStart وEnd وحالة النافذة.", "راجع Duration وBuffers في Offering وتأكد أن النافذة تتسع لـSlot واحدة على الأقل.", "راجع Date overrides.", "راجع Booking policy وEarliest bookable date.", "اختبر Timezone والشهر الصحيحين."]),
  troubleshooting("split-window-problem", "فترتان في اليوم تعطيان نتائج غير متوقعة", ["overlap", "two windows", "فترتين"], "/admin/availability", ["تأكد أن النافذتين لنفس Offering واليوم المقصود.", "تأكد أن End الأولى لا تتجاوز Start الثانية.", "راجع Buffers وDuration في Offering.", "احذف/أرشف النافذة المكررة فقط.", "راجع Calendar overview ثم صفحة العميل."]),
  troubleshooting("earliest-date-problem", "أول تاريخ للحجز أبعد من المتوقع", ["earliest date", "advance days", "تاريخ الحجز"], "/admin/availability", ["راجع Minimum advance booking days.", "تذكر أن القيمة تغلق أيام تقويم كاملة.", "راجع Booking timezone قرب منتصف الليل.", "راجع Date override على أول يوم متوقع.", "راجع وجود Weekly availability في ذلك اليوم."]),
  troubleshooting("offering-not-selectable", "Offering لا تظهر في Sessions أوPrograms", ["select offering", "missing offering", "مش موجودة"], "/admin/offerings", ["تأكد أنها ليست Archived.", "للـPrograms تأكد أن Scheduling type = Scheduled program.", "تأكد من اكتمال حفظ Offering.", "حدّث الصفحة بعد التعديل.", "استخدم Sessions فقط للنمط الذي تدعمه الواجهة الحالية."]),
  troubleshooting("location-required", "لا يمكن حفظ Offline أوHybrid بدون Location", ["location required", "offline", "hybrid"], "/admin/locations", ["أنشئ Location فعالة.", "راجع Attendance في Offering.", "اختر Location في Session أوProgram/Occurrence.", "تأكد أن المكان غير Archived."]),
  troubleshooting("capacity-held", "السعة تبدو ممتلئة بسبب Held", ["held", "capacity full", "remaining zero"], "/admin/bookings", ["راجع Total وBooked وHeld وRemaining.", "انتظر مهلة الـHold إذا كان العميل لم يكمل.", "راجع Worker/maintenance من الحالة التشغيلية إذا ظلت Holds غير منتهية، بدون تعديل قاعدة البيانات من الدليل.", "لا ترفع Capacity إلا إذا كان هناك قرار تشغيلي حقيقي."]),
  troubleshooting("price-not-applied", "Price group أوEarly bird لا يطبقان", ["price group", "early bird", "country", "ip"], "/admin/offerings", ["راجع عملة ومبلغ المجموعة.", "راجع الدول المرتبطة وعدم التعارض.", "راجع تاريخ ووقت نهاية Early bird.", "تأكد أن الطلب جديد وليس سجلًا قديمًا بسعر محفوظ.", "اختبر Fallback وبلدًا مختلفًا بطريقة موثوقة."]),
  troubleshooting("media-not-ready", "الملف مفقود أوProcessing أوFailed", ["media failed", "upload", "processing", "r2"], "/admin/cms", ["تأكد أنك ضغطت Upload selected file بعد اختيار الملف.", "انتظر اكتمال Uploading وChecking file.", "حدّث Media Library وراجع Processing state/error.", "تحقق أن نوع الملف مقبول للحقل.", "لا تستخدم Animation bundle قبل Ready."]),
  troubleshooting("media-not-updated", "الصورة أوالفيديو القديم ما زال ظاهرًا", ["old image", "cache", "replace media"], "/admin/cms", ["تأكد أن Asset الجديدة مختارة في السيكشن الصحيح.", "اضغط Save section.", "راجع حالة Section والصفحة.", "افتح Preview ثم الصفحة العامة في نافذة خاصة.", "تحقق من URL الأصل قبل اعتبار المشكلة Cache."]),
  troubleshooting("content-not-public", "Page أوLegal أوBlog ما زالت غير ظاهرة", ["draft", "scheduled", "publication", "مش منشورة"], "/admin/cms", ["راجع Status للسجل نفسه.", "راجع Published at إذا كانت Scheduled.", "للصفحات راجع حالات Sections المطلوبة.", "راجع Publication error وPreview.", "تأكد أن Navigation لا تشير إلى Slug مختلفة."]),
  troubleshooting("calendar-sync-failed", "Calendar أوMeet sync فشل", ["calendar failed", "meet missing", "retry sync"], "/admin/integrations", ["راجع اتصال Integrations أولًا.", "راجع Timezone والبيانات المطلوبة للموعد.", "لا تنشئ سجلًا مكررًا.", "استخدم Retry calendar sync على Program/السجل الأصلي.", "تحقق من Google Calendar بعد ظهور نجاح."]),
  troubleshooting("payment-inconsistent", "Payment معلقة أوغير متطابقة مع Booking", ["payment pending", "reconcile", "payment mismatch"], "/admin/payments", ["طابق Payment reference وBooking reference والمبلغ والعملة.", "راجع Provider status والتوقيت.", "استخدم Reconcile/Retry مرة واحدة إن كان متاحًا.", "حدّث وانتظر نتيجة المعالجة.", "إذا استمر التعارض راجع المزود بالمراجع بدل إنشاء دفع جديد عشوائيًا."]),
  troubleshooting("email-not-delivered", "العميل لم يستلم الإيميل", ["email failed", "not delivered", "spam"], "/admin/emails", ["تأكد من عنوان العميل.", "ابحث عن Delivery ونوع الرسالة الصحيح.", "راجع Status والخطأ.", "اطلب من العميل مراجعة Spam عند Delivered.", "صحح Template/العنوان إن لزم ثم Retry مرة واحدة."]),
];

const checklists: GuideEntry[] = [
  {
    id: "appointment-launch-checklist",
    title: "Checklist إطلاق Appointment service",
    summary: "راجع هذه القائمة قبل مشاركة رابط خدمة المواعيد.",
    aliases: ["appointment launch", "checklist", "إطلاق خدمة"],
    href: "/admin/offerings",
    blocks: [{ heading: "جاهزية الإطلاق", items: ["Offering محفوظة ومنشورة بعنوان ووصف وSlug صحيحين.", "Appointment slots مختارة والمدة والـBuffers والسعة صحيحة.", "السعر وBooking mode مجربان.", "Availability منشورة بلا تداخل وDate overrides مراجعة.", "Booking policy وTimezone صحيحتان.", "نموذج الحجز والإيميلات وتجربة العميل الكاملة ناجحة."], tone: "success" }],
  },
  {
    id: "session-launch-checklist",
    title: "Checklist إطلاق Session أوEvent ثابت",
    summary: "راجع الموعد والسعة والمكان والظهور قبل الإعلان.",
    aliases: ["session launch", "event launch", "checklist"],
    href: "/admin/sessions",
    blocks: [{ heading: "جاهزية الإطلاق", items: ["Offering الصحيحة مختارة.", "Starts وEnds وTimezone راجعتهم بشريًا.", "Mode وLocation متوافقان.", "Capacity مناسبة.", "Status والنشر والسعر صحيحون.", "Calendar/Meet والإيميل جُرّبا."], tone: "success" }],
  },
  {
    id: "program-launch-checklist",
    title: "Checklist إطلاق Program أوCourse",
    summary: "تأكد أن التسجيل الواحد يغطي الجدول الكامل الصحيح.",
    aliases: ["program launch", "course launch", "checklist"],
    href: "/admin/programs",
    blocks: [{ heading: "جاهزية الإطلاق", items: ["Offering = Scheduled program.", "Program title وفترة التسجيل والسعة صحيحة.", "كل Occurrences مرتبة بأوقات وTimezones وأماكن صحيحة.", "السعر وBooking mode مجربان.", "Publish نجح وCalendar sync لكل موعد سليم.", "رحلة التسجيل والإيميلات تمت تجربتها."], tone: "success" }],
  },
  {
    id: "cms-launch-checklist",
    title: "Checklist نشر صفحة أوContent",
    summary: "مراجعة المحتوى والوسائط والـSEO والروابط قبل النشر.",
    aliases: ["cms launch", "publish page", "checklist", "seo"],
    href: "/admin/cms",
    blocks: [{ heading: "جاهزية النشر", items: ["Title وSlug وحالة الصفحة صحيحة.", "كل Sections محفوظة ومرتبة ومكتملة.", "الصور والفيديوهات Ready ولها Alt text عند الحاجة.", "كل الروابط تعمل.", "Preview راجعت Desktop وMobile.", "SEO وSocial image مضبوطتان.", "Navigation تشير للرابط الصحيح بعد النشر."], tone: "success" }],
  },
  {
    id: "paid-launch-checklist",
    title: "Checklist جاهزية الحجز المدفوع",
    summary: "لا تنشر Paid قبل اختبار السعر والدفع والتأكيد.",
    aliases: ["paid launch", "payment checklist", "دفع"],
    href: "/admin/payments",
    blocks: [{ heading: "جاهزية الدفع", items: ["Booking mode = Paid وRequires payment متوافقان.", "Base amount وPrice groups والعملات صحيحة.", "Early bird إن وجدت لها مبلغ وموعد نهاية صحيحان.", "بوابة الدفع وبيئة الإنتاج جاهزتان.", "Payment وBooking ينتقلان للحالات المتوقعة في تجربة كاملة.", "إيميل التأكيد يصل ولا توجد عملية اختبار غير مقصودة متروكة."], tone: "success" }],
  },
];

export const guideSections: GuideSection[] = [
  {
    id: "understand-system",
    title: "افهم النظام أولًا",
    description: "ابدأ هنا لتعرف الفرق بين السجلات وتختار المسار الصحيح قبل إدخال البيانات.",
    entries: understandSystem,
  },
  {
    id: "playbooks",
    title: "السيناريوهات خطوة بخطوة",
    description: "خطوات تشغيل كاملة مع التأثير والأخطاء الشائعة وطريقة التراجع.",
    entries: playbooks,
  },
  {
    id: "page-reference",
    title: "مرجع صفحات الداشبورد",
    description: "ما الذي تملكه كل صفحة، وما الحقول المهمة، وما الذي يجب الحذر منه.",
    entries: pageReferences,
  },
  {
    id: "troubleshooting",
    title: "حل المشاكل",
    description: "تشخيص مرتب لأكثر الحالات التي تمنع الظهور أوالحجز أوالدفع أوالإرسال.",
    entries: troubleshootingEntries,
  },
  {
    id: "checklists",
    title: "قوائم المراجعة قبل الإطلاق",
    description: "راجع القائمة المناسبة قبل مشاركة أي رابط مع العملاء.",
    entries: checklists,
  },
];

export const guideNavigation = guideSections.map(({ id, title }) => ({ id, title }));

const normalize = (value: string) => value.trim().toLocaleLowerCase("ar");

const searchableText = (entry: GuideEntry) => normalize([
  entry.title,
  entry.summary,
  ...entry.aliases,
  ...entry.blocks.flatMap((block) => [block.heading, ...block.items]),
].join(" "));

export const searchGuideSections = (query: string) => {
  const needle = normalize(query);
  if (!needle) return guideSections;
  return guideSections
    .map((section) => ({
      ...section,
      entries: section.entries.filter((entry) => searchableText(entry).includes(needle)),
    }))
    .filter((section) => section.entries.length > 0);
};
